export const PREFECTURES = [
  { cd: 1,  name: '北海道' },
  { cd: 2,  name: '青森' },
  { cd: 3,  name: '岩手' },
  { cd: 4,  name: '宮城' },
  { cd: 5,  name: '秋田' },
  { cd: 6,  name: '山形' },
  { cd: 7,  name: '福島' },
  { cd: 8,  name: '茨城' },
  { cd: 9,  name: '栃木' },
  { cd: 10, name: '群馬' },
  { cd: 11, name: '埼玉' },
  { cd: 12, name: '千葉' },
  { cd: 13, name: '東京' },
  { cd: 14, name: '神奈川' },
  { cd: 15, name: '新潟' },
  { cd: 16, name: '富山' },
  { cd: 17, name: '石川' },
  { cd: 18, name: '福井' },
  { cd: 19, name: '山梨' },
  { cd: 20, name: '長野' },
  { cd: 21, name: '岐阜' },
  { cd: 22, name: '静岡' },
  { cd: 23, name: '愛知' },
  { cd: 24, name: '三重' },
  { cd: 25, name: '滋賀' },
  { cd: 26, name: '京都' },
  { cd: 27, name: '大阪' },
  { cd: 28, name: '兵庫' },
  { cd: 29, name: '奈良' },
  { cd: 30, name: '和歌山' },
  { cd: 31, name: '鳥取' },
  { cd: 32, name: '島根' },
  { cd: 33, name: '岡山' },
  { cd: 34, name: '広島' },
  { cd: 35, name: '山口' },
  { cd: 36, name: '徳島' },
  { cd: 37, name: '香川' },
  { cd: 38, name: '愛媛' },
  { cd: 39, name: '高知' },
  { cd: 40, name: '福岡' },
  { cd: 41, name: '佐賀' },
  { cd: 42, name: '長崎' },
  { cd: 43, name: '熊本' },
  { cd: 44, name: '大分' },
  { cd: 45, name: '宮崎' },
  { cd: 46, name: '鹿児島' },
  { cd: 47, name: '沖縄' },
  { cd: 48, name: '芸文' },
  { cd: 98, name: '学連' },
] as const;

export const PREFECTURE_NAMES = PREFECTURES.map(p => p.name);
export const DEFAULT_AFFILIATION = '大阪';
